// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuISwgIRHdGqYI6_hPYWIZsU2i4utiJrg',
    appId: '1:334571748621:web:41837dcd4a7d0cec73c444',
    messagingSenderId: '334571748621',
    projectId: 'otsukaresan-fec39',
    authDomain: 'otsukaresan-fec39.firebaseapp.com',
    databaseURL:
        'https://otsukaresan-fec39-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'otsukaresan-fec39.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOx0ejzQkYfseKnk-BeMNkchW_NAY5rYA',
    appId: '1:334571748621:android:c62abaac3bf0e9d573c444',
    messagingSenderId: '334571748621',
    projectId: 'otsukaresan-fec39',
    databaseURL:
        'https://otsukaresan-fec39-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'otsukaresan-fec39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ46jUHb1ZwzzladjdcX6JVfm0eQ1jaHw',
    appId: '1:334571748621:ios:d81f35d53d73e0e173c444',
    messagingSenderId: '334571748621',
    projectId: 'otsukaresan-fec39',
    databaseURL:
        'https://otsukaresan-fec39-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'otsukaresan-fec39.firebasestorage.app',
    iosBundleId: 'com.example.otsukareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ46jUHb1ZwzzladjdcX6JVfm0eQ1jaHw',
    appId: '1:334571748621:ios:d81f35d53d73e0e173c444',
    messagingSenderId: '334571748621',
    projectId: 'otsukaresan-fec39',
    databaseURL:
        'https://otsukaresan-fec39-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'otsukaresan-fec39.firebasestorage.app',
    iosBundleId: 'com.example.otsukareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuISwgIRHdGqYI6_hPYWIZsU2i4utiJrg',
    appId: '1:334571748621:web:530eede1b53f999773c444',
    messagingSenderId: '334571748621',
    projectId: 'otsukaresan-fec39',
    authDomain: 'otsukaresan-fec39.firebaseapp.com',
    databaseURL:
        'https://otsukaresan-fec39-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'otsukaresan-fec39.firebasestorage.app',
  );
}
